<?php
namespace aura\http;

/**
 * Test class for Cookies.
 * Generated by PHPUnit on 2011-05-10 at 11:16:02.
 */
class CookiesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cookies
     */
    protected $cookies;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->cookies = new Cookies;
        MockHttp::reset();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @todo Implement testGetAll().
     */
    public function testSetAndGetAll()
    {
        $this->cookies->setAll(array(
            'login' => array(
                'value' => '1234567890',
            ),
            'usrid' => array(
                'value' => '0987654321'
            ),
        ));
        
        $actual = $this->cookies->getAll();
        $expect = array (
          'login' => 
          array (
            'value' => '1234567890',
            'expire' => 0,
            'path' => NULL,
            'domain' => NULL,
            'secure' => false,
            'httponly' => true,
          ),
          'usrid' => 
          array (
            'value' => '0987654321',
            'expire' => 0,
            'path' => NULL,
            'domain' => NULL,
            'secure' => false,
            'httponly' => true,
          ),
        );
        
        $this->assertSame($expect, $actual);
    }
    /**
     * @todo Implement testSend().
     */
    public function testSend()
    {
        $this->cookies->setAll(array(
            'login' => array(
                'value' => '1234567890',
            ),
            'usrid' => array(
                'value' => '0987654321'
            ),
        ));
        
        $this->cookies->send();
        
        $expect = array (
          0 => 
          array (
            'name' => 'login',
            'value' => '1234567890',
            'expire' => 0,
            'path' => NULL,
            'domain' => NULL,
            'secure' => false,
            'httponly' => true,
          ),
          1 => 
          array (
            'name' => 'usrid',
            'value' => '0987654321',
            'expire' => 0,
            'path' => NULL,
            'domain' => NULL,
            'secure' => false,
            'httponly' => true,
          ),
        );

        $this->assertSame($expect, MockHttp::$cookies);
    }
}
