<?php
namespace Aura\Http;

use Aura\Http\Cookie\Factory as CookieFactory;
use Aura\Http\Cookie\Collection as Cookies;
use Aura\Http\Cookie\JarFactory as CookieJarFactory;
use org\bovigo\vfs\vfsStream;

/**
 * Test class for Cookies.
 * Generated by PHPUnit on 2011-05-10 at 11:16:02.
 */
class CookiesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cookies
     */
    protected $cookies;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->cookies = new Cookies(new CookieFactory);
    }

    protected function newCookie(
        $name, 
        $value    = null, 
        $expire   = null, 
        $path     = null, 
        $domain   = null, 
        $secure   = false, 
        $httponly = true
    )
    {
        return new Cookie(
            $name, 
            $value, 
            $expire, 
            $path, 
            $domain, 
            $secure, 
            $httponly
        );
    }

    public function test__get()
    {
        $this->cookies->set('foo_bar', array());

        $this->assertEquals($this->newCookie('foo_bar'), $this->cookies->foo_bar);
    }
    
    public function test__isset()
    {
        $this->cookies->set('foo_bar', array());

        $this->assertTrue(isset($this->cookies->foo_bar));
        $this->assertFalse(isset($this->cookies->Bar_Foo));
    }
    
    public function test__unset()
    {
        $this->cookies->set('foo_bar', array());

        $this->assertTrue(isset($this->cookies->foo_bar));

        unset($this->cookies->foo_bar);

        $this->assertFalse(isset($this->cookies->foo_bar));
    }
    
    public function testCount()
    {
        $this->cookies->set('Foo', array());
        $this->cookies->set('max', array('value' => 'hi'));

        $this->assertEquals(2, count($this->cookies));
    }
    
    public function testGetIterator()
    {
        $this->assertInstanceOf('\IteratorAggregate', $this->cookies);
        $this->assertInstanceOf('\ArrayIterator', $this->cookies->getIterator());
    }

    public function testAddWithCookie()
    {
        $cookie  = new Cookie('Foo', 'Bar', null, null, null, null, null);

        $this->cookies->set($cookie);

        $this->assertSame($cookie, $this->cookies->Foo);
    }

    public function testsetOneFromHeader()
    {
        $set      = 'name=value; Expires=Wed, 09 Jun 2021 10:18:14 GMT;httponly';

        $this->cookies->setOneFromHeader($set);

        $expected = ['name' => $this->newCookie('name', 'value', 'Wed, 09 Jun 2021 10:18:14 GMT')];
        $this->assertEquals($expected, $this->cookies->getAll());
    }

    public function testSetAndGetAll()
    {
        $this->cookies->setAll([
            'login' => [
                'value' => '1234567890',
            ],
            'usrid' => [
                'value' => '0987654321'
            ],
        ]);
        
        $actual = $this->cookies->getAll();
        $expect = [
          'login' => $this->newCookie(
            'login',
            '1234567890',
            0,
            NULL,
            NULL,
            false,
            true)
          ,
          'usrid' => $this->newCookie(
            'usrid',
            '0987654321',
            0,
            NULL,
            NULL,
            false,
            true),
        ];
        
        $this->assertEquals($expect, $actual);
    }
    
    public function test__toString()
    {
        $this->cookies->setAll([
            'login' => [
                'value' => '1234567890',
            ],
            'usrid' => [
                'value' => '0987654321'
            ],
        ]);
        
        $actual = $this->cookies->__toString();
        $expect = "login=1234567890;usrid=0987654321";
        $this->assertSame($actual, $expect);
    }
    
    public function testSetAllFromJar()
    {
        $structure = array('resource.txt' => '');
        $root = vfsStream::setup('root', null, $structure);
        $file = vfsStream::url('root/resource.txt');
        
        $storage = fopen($file, 'r+');
        $text = implode(PHP_EOL, [
            "# Netscape HTTP Cookie File",
            "# http://curl.haxx.se/rfc/cookie_spec.html",
            "# This file was generated by Aura. Edit at your own risk!",
            "www.example.com\tFALSE\t/\tFALSE\t1645033667\tfoo\tbar",
            "#HttpOnly_.example.com\tTRUE\t/path\tTRUE\t1645033667\tbar\tfoo",
        ]);
        fwrite($storage, $text);
        
        $jar_factory = new CookieJarFactory;
        
        $jar = $jar_factory->newInstance($storage);
        
        $this->cookies->setAllFromJar($jar, 'http://www.example.com');
        $actual = $this->cookies->__toString();
        
        // @todo Shouldn't this actually show *both* cookies?
        $expect = 'foo=bar';
        $this->assertSame($expect, $actual);
    }
}
